const CURRENCY_CODES = [
  { id: "INR", value: "Indian Rupee" },
  { id: "EUR", value: "Euro" },
  { id: "USD", value: "US Dollar" },
  { id: "JPY", value: "Japanese Yen" },
  { id: "BGN", value: "Bulgarian Lev" },
  { id: "CZK", value: "Czech Republic Koruna" },
  { id: "DKK", value: "Danish Krone" },
  { id: "GBP", value: "British Pound Sterling" },
  { id: "HUF", value: "Hungarian Forint" },
  { id: "PLN", value: "Polish Zloty" },
  { id: "RON", value: "Romanian Leu" },
  { id: "SEK", value: "Swedish Krona" },
  { id: "CHF", value: "Swiss Franc" },
  { id: "ISK", value: "Icelandic Króna" },
  { id: "NOK", value: "Norwegian Krone" },
  { id: "HRK", value: "Croatian Kuna" },
  { id: "RUB", value: "Russian Ruble" },
  { id: "TRY", value: "Turkish Lira" },
  { id: "AUD", value: "Australian Dollar" },
  { id: "BRL", value: "Brazilian Real" },
  { id: "CAD", value: "Canadian Dollar" },
  { id: "CNY", value: "Chinese Yuan" },
  { id: "HKD", value: "Hong Kong Dollar" },
  { id: "IDR", value: "Indonesian Rupiah" },
  { id: "ILS", value: "Israeli New Sheqel" },
  { id: "KRW", value: "South Korean Won" },
  { id: "MXN", value: "Mexican Peso" },
  { id: "MYR", value: "Malaysian Ringgit" },
  { id: "NZD", value: "New Zealand Dollar" },
  { id: "PHP", value: "Philippine Peso" },
  { id: "SGD", value: "Singapore Dollar" },
  { id: "THB", value: "Thai Baht" },
  { id: "ZAR", value: "South African Rand" },
];

export default CURRENCY_CODES;
